import Head from "next/head";
import LandingPage from "./landingPage/landingPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MOM App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </div>
  );
}
